default_context:
  project_name: '5LEGS Automation'
  project_slug: '5legs-automation'
  domain_main: '5legs.net'
  domain_staging: 'stag.5legs.net'
  docker_swarm_stack_name_main: '5legs-net'
  docker_swarm_stack_name_staging: 'stag-5legs-net'
  secret_key: 'd41d8cd98f00b204e9800998ecf8427e'
  first_superuser: 'admin@5legs.net'
  first_superuser_password: 'azerty123'
  backend_cors_origins: 'http://localhost, http://localhost:4200, http://localhost:3000, http://localhost:8080, https://localhost, https://localhost:4200, https://localhost:3000, https://localhost:8080, http://dev.5legs.net, https://stag.5legs.net, https://5legs.net, http://local.dockertoolbox.tiangolo.com, http://localhost.tiangolo.com'
  smtp_port: '587'
  smtp_host: 'smtp.office365.com'
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@5legs.net'
  postgres_password: '05a671c66aefea124cc08b76ea6d30bb'
  pgadmin_default_user: 'admin@5legs.net'
  pgadmin_default_user_password: 'azerty123'
  traefik_constraint_tag: '5legs.net'
  traefik_constraint_tag_staging: 'stag.5legs.net'
  traefik_public_network: 'proxy'
  traefik_public_constraint_tag: 'proxy'
  flower_auth: 'admin:azerty123'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
